name: CI Github Pages
on:
  #监听push操作
  push:
    branches:
      - docs # 这里只配置了docs分支，所以只有推送docs分支才会触发以下任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 官方action，将代码拉取到虚拟机
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist